---
title: "iPTMnet Data Survey"
author: "Brian M. Schilder"
date: "12/19/2017"
output: html_document
---
```{r}
setwd("~/Desktop/x2k/Kinase_datasets/iPTMnet/")
```

# UniProtAC_GeneSymbol converter
```{r}
# all HUMAN UniProtACs
  #gz = read.delim("../../General_Resources/UniProt/HUMAN_9606_idmapping_selected.tab.gz")
  #HUMAN_allUniProtACs <-read.delim("../../General_Resources/UniProt/HUMAN_9606_idmapping_selected.tab", header=F)[1]
  #write.csv(HUMAN_allUniProtACs, "../../General_Resources/UniProt/HUMAN_allUniProtACs.csv")

# all MOUSE UniProtACs
  #gz = gzfile("../../General_Resources/UniProt/MOUSE_10090_idmapping_selected.tab.gz")
  #MOUSE_allUniProtACs <-read.delim(gz, header=F)[1]
  #write.csv(HUMAN_allUniProtACs, "../../General_Resources/UniProt/MOUSE_allUniProtACs.csv")
```

# iPTMnet
## Score list
```{r}
# kinase-substrate edge list from iPTMnet.
iPTMnet_score <-read.delim("score.txt", header=F)
colnames(iPTMnet_score) <-c("substrate_AC", "site", "enzyme_AC", "ptm_type", "score")
iPTMnet_score$enzyme_AC <-gsub("PR:|MIM_MORBID_ACC:", "", iPTMnet_score$enzyme_AC)
iPTMnet_score$substrate_AC <-gsub("PR:|MIM_MORBID_ACC:", "", iPTMnet_score$substrate_AC)
# Only include those that have enzyme_AC interaction
iPTMnet_score <-subset(iPTMnet_score, enzyme_AC != "")

write.csv(iPTMnet_score, "score_condensed.csv")
# Assess Size
length(unique(iPTMnet_score$substrate_AC))
length(unique(iPTMnet_score$enzyme_AC))
```

## iPTMnet protein metadata list
```{r}
readme <-read.delim("readme.txt", header=F )
# *** Edited protein file in Python (waaaaay faster) ****
# Check genes with "fusion" in the name!
#prot_orig <-read.delim("protein.txt", header=F)
prot <-read.delim("protein_edit.txt", header=F)
colnames(prot) <- c(as.character(readme[22:28,2]),"GeneNames")

iPTMnet_score_prot <-iPTMnet_score[iPTMnet_score$enzyme_AC %in% prot$UniProtAC,]
dim(iPTMnet_score_prot)
iPTMnet_score_prot <-iPTMnet_score_prot[iPTMnet_score_prot$substrate_AC %in% prot$UniProtAC,]
dim(iPTMnet_score_prot)
# Get the GeneSymbol(s) for each enzymeAC/substrateAC and add to new col
enzyme_GeneName = c()
substrate_GeneName = c()
for(row.num in 1:nrow(iPTMnet_score_prot)){
  # Enzyme
  enzymeAC <- as.character(iPTMnet_score_prot[row.num,]$enzyme_AC)
  enzyme_GeneName <- c(enzyme_GeneName, as.character(prot[prot$UniProtAC==enzymeAC,]$GeneNames))
  # Substrate
  substrateAC <- as.character(iPTMnet_score_prot[row.num,]$substrate_AC)
  substrate_GeneName <- c(substrate_GeneName, as.character(prot[prot$UniProtAC==substrateAC,]$GeneNames))
}
iPTMnet_score_prot$enzyme_GeneName <-enzyme_GeneName
iPTMnet_score_prot$substrate_GeneName <-substrate_GeneName
head(iPTMnet_score_prot)
save(iPTMnet_score_prot, file="iPTMnet_score_prot.RD")
```

## Convert all genes to human genes
```{r}
load("iPTMnet_score_prot.RD")

# Convert any mouse gene to human genes using NCBI Homologene mappings
orthos_species.key <-read.delim("../../General_Resources/Homologue_Mapping/taxid_taxname", header=F, col.names=c("SpeciesID", "SpeciesName"))
orthos <- read.delim("../../General_Resources/Homologue_Mapping/homologene.data",header=F, col.names=c("GeneNum","SpeciesID","V3","GeneName","V5","TranscriptID"))
#Just mouse and human
orthos_filt<- subset(orthos, SpeciesID=="10090"|SpeciesID=="9606") 
orthos_filt[orthos_filt$SpeciesID=="10090", "SpeciesName"] <- "Mouse"
orthos_filt[orthos_filt$SpeciesID=="9606", "SpeciesName"] <- "Human"

Mouse = subset(orthos_filt, SpeciesName=="Mouse")
colnames(Mouse) <-paste("Mouse",colnames(Mouse),sep=".")
Human = subset(orthos_filt, SpeciesName=="Human")
colnames(Human) <-paste("Human",colnames(Human),sep=".")

Orthos = merge(Mouse, Human, by.x="Mouse.GeneNum", by.y="Human.GeneNum")

# Create a new col "Converted_GeneSymbol"
Converted_enzymeGeneSymbol <- c()
Converted_substrateGeneSymbol <- c()
for(row.num in 1:nrow(iPTMnet_score_prot)){
  # Enzymes
  enzyme_GeneQuery <-strsplit(as.character(iPTMnet_score_prot[row.num,]$enzyme_GeneName),",")[[1]]
  convertedEnzymes = c()
  for(gene in enzyme_GeneQuery){
    # If it's a mouse gene, convert to human
    if(gene %in% Orthos$Mouse.GeneName){
      convertedEnzymes <- c(convertedEnzymes, as.character(Orthos[Orthos$Mouse.GeneName==gene,"Human.GeneName"]) ) }
    # If gene human, or if it can't be identified in HomoloGene, add as is
    else{convertedEnzymes <- c(convertedEnzymes, gene)}
  }
  # Add to vector
    Converted_enzymeGeneSymbol <-c(Converted_enzymeGeneSymbol, paste(convertedEnzymes, collapse=","))
    
  # Substrates
  substrate_GeneQuery <-strsplit(as.character(iPTMnet_score_prot[row.num,]$substrate_GeneName),",")[[1]]
  convertedSubstrates = c()
  for(gene in substrate_GeneQuery){
    # If it's a mouse gene, convert to human
    if(gene %in% Orthos$Mouse.GeneName){
      convertedSubstrates <- c(convertedSubstrates, as.character(Orthos[Orthos$Mouse.GeneName==gene,"Human.GeneName"]) ) }
    # If gene human, or if it can't be identified in HomoloGene, add as is
    else{convertedSubstrates <- c(convertedSubstrates, gene)}
    }
    # Add to vector
    Converted_substrateGeneSymbol <-c(Converted_substrateGeneSymbol, paste(convertedSubstrates, collapse=","))
  }
iPTMnet_score_prot$Converted_enzymeGeneSymbol <- Converted_enzymeGeneSymbol
iPTMnet_score_prot$Converted_substrateGeneSymbol <- Converted_substrateGeneSymbol

```

## Subset iPTMnet to only kinase enzymes
```{r}
## Import kinome
### From kinase.com
kinome <- data.frame(read_excel("~/Desktop/x2k/General_Resources/Kinase.com/Kinome_Hsap.xls", na=""))$Entrez_Symbol
kinome <- kinome[!is.na(kinome)]
length(kinome)
### From KEA file
kinome2 <- read.delim("~/Desktop/x2k/data/KEA/kea_ranks.txt", head=F)[,1]
length(kinome2)
kinome=kinome2

# Filter by kinases
one_enzymeGeneSymbol <- c()
one_substrateGeneSymbol <- c()
for(row.num in 1:nrow(iPTMnet_score_prot)){
  # Enzyme
  enzyme_GeneSymbols <-strsplit(as.character(iPTMnet_score_prot[row.num,"Converted_enzymeGeneSymbol"]),",")[[1]]
  kinome_overlap <- enzyme_GeneSymbols %in% kinome
  if(sum(kinome_overlap)>0){
    one_enzymeGeneSymbol <-c(one_enzymeGeneSymbol, enzyme_GeneSymbols[kinome_overlap][1])
  }
  else{one_enzymeGeneSymbol <- c(one_enzymeGeneSymbol, "Drop_Me")}
  
  # Substrate
  substrate_GeneSymbols <-strsplit(as.character(iPTMnet_score_prot[row.num,"Converted_substrateGeneSymbol"]),",")[[1]]
  one_substrateGeneSymbol <- c(one_substrateGeneSymbol, substrate_GeneSymbols[1])
}
# Add new cols
iPTMnet_score_prot$one_enzymeGeneSymbol <- one_enzymeGeneSymbol
iPTMnet_score_prot$one_substrateGeneSymbol <- one_substrateGeneSymbol
# Subset to kinome
iPTMnet_score_kinome <-subset(iPTMnet_score_prot, first_enzymeGeneSymbol!="Drop_Me")
head(iPTMnet_score_kinome)

# Total number of enzyme-substrate interactions in iPTMnet
dim(iPTMnet_score)[1]
# Number of kinase-substrate interactions in iPTMnet
dim(iPTMnet_score_kinome)[1]
# Number of unique kinases in iPTMnet
length(unique(iPTMnet_score_kinome$one_enzymeGeneSymbol)) # 381 using KEA kinome, 375 using kinome.com
# Number of unique substrates in iPTMnet
length(unique(iPTMnet_score_kinome$one_substrateGeneSymbol))
```

## Create iPTMnet GMT file
### [Kinase] [Substrate] [Score]
```{r}
gmt_df <-subset(iPTMnet_score_kinome, select=c("one_substrateGeneSymbol", "one_enzymeGeneSymbol", "score"))
write.table(gmt_df, "iPTMnet_kinome_scores.GMT.txt", sep = "\t", col.names = F, row.names = F, quote = F)
```

### [Kinase] [Kinase] [Substrate] [Substrate] [Substrate] [....]
```{r}
library(dplyr)
unique_kinases <- unique(gmt_df$one_enzymeGeneSymbol)
combined_substrates <- c()
for(kinase in unique_kinases){
  filt <-gmt_df[gmt_df$one_enzymeGeneSymbol==kinase, ]
  # Get average score for each substrate within kinase
  filt <- filt %>% group_by(one_substrateGeneSymbol) %>% summarise(mean_score=mean(score)) %>% as.data.frame()
  # Order by score
  ord <- filt[order(filt$mean_score, decreasing = T),] 
  # Combine substrates
  substrates <-filt$one_substrateGeneSymbol
  combined_substrates <- c(combined_substrates, paste(substrates, collapse="\t"))
} 
new_gmt <-data.frame(kinase1=unique_kinases, space=rep("\t",length(unique_kinases)), Substrates=combined_substrates)

# Filter kinases that have less than 5 substrates
bool <- c()
for(row.num in 1:nrow(new_gmt)){
  substrates <-strsplit(as.character(new_gmt[row.num, ]$Substrates),"\t")[[1]]
  if(length(substrates)>=5){
    bool <- c(bool, TRUE)
  }
  else{bool <- c(bool, FALSE)}
}

filt_gmt <-new_gmt[bool, ]
dim(new_gmt)
dim(filt_gmt)
# Write to GMT
write.table(filt_gmt, "iPTMnet_kinome.GMT.txt", sep = "\t", col.names = F, row.names = F, quote = F)
```


# KEA
```{r}
# Import KEA
KEA <-read.csv("~/Desktop/x2k/data/KEA/kinase-protein_interactions.csv", header=F)
colnames(KEA) <-c("Class", "Group", "Kinase", "Substrate", "PubMed_ID")
# Number of kinase-protein interactions in KEA
dim(KEA)[1]
```

# iPTMnet + KEA overlap

```{r}
iPTMnet_interactions <-paste(iPTMnet_kinome_merged$enzyme_GeneSymbol,
                             iPTMnet_kinome_merged$substrate_GeneSymbol, sep="_")
KEA_interactions <-paste(KEA$Kinase, KEA$Substrate,sep="_")

# Number of overlapping kinase-substrate interactions between iPTMnet and KEA
overlapping_interactions<-sum(iPTMnet_interactions %in% KEA_interactions)

overlapping_interactions / length(iPTMnet_interactions)
```



